### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by gwenf** [Free-Code-Camp-Indy/free-code-camp-indy.github.io#12]
![img_9091](https://cloud.githubusercontent.com/assets/10039233/19544411/b585840c-964c-11e6-9053-4f4a057581c0.JPG)

**Comment by gwenf** [comment]
That pic is of the galleries. You can click on a gallery to navigate to a page with all the pictures inside that gallery.

We were thinking of doing the display Pinterest style using: http://masonry.desandro.com/

**Comment by gwenf** [comment]
![img_9091](https://cloud.githubusercontent.com/assets/10039233/19544543/c04b074e-964d-11e6-971e-eaa21233a408.JPG)

**Comment by mattattaq** [comment]
The colored boxes denote where the meetup took place, say at club cyberia, etc.. etc..
The first line of blue text should be the location
and the green text should be details about the album

**Comment by mattattaq** [comment]
The Cool gallery banner is just a banner that one of my designers of myself can make to show what page you're on.

**Comment by gwenf** [comment]
Design Doc: https://docs.google.com/document/d/1PBaRWUjsR6IVD2P5Tz7H1N6wzE8awM7oETdUfBA9o1Q/edit

**Comment by blackbetty** [comment]
Do we have a preference on image hosting?

**Comment by gwenf** [comment]
@blackbetty I don't really know the best place for for it. Maybe you can ask @TheJaredWilcurt

**Comment by TheJaredWilcurt** [comment]
We'd discussed pulling in images from the Meetup API, and potentially storing some of the common/reused images in the repo. Like the thumbnails that denote the different locations (Iron Yard, The Hatch, Club Cyberia, etc.).

But there was no definitive choice. This was one of the areas of the site that was left intentionally vague since "a gallery" can be as simple as this:

```
<a href="big-image.jpg" target="_blank"><img src="small-image.jpg" alt="alt text" /></a>
```

repeated a bunch of times. To as complex as a masonry layout pulled in from multiple API's grouped into sub albums from a JSON payload with a lightbox for large images.

Since we have varying levels of experience from our volunteers we didn't set any expectations other than "make a gallery" so that we could get something up based on whatever the person who volunteers thinks they can do.

**Comment by blackbetty** [comment]
gotcha, just wanted to be sure.

**Comment by gwenf** [comment]
@blackbetty have you been able to work on this at all? 
This is the last outstanding item besides design updates.

**Comment by jmsMaupin1** [comment]
So, how do we want to handle navigating between the gallery folders and the images? 

Currently after clicking a folder I have the page set up to hide the folder and show the correct images. To make this work long term I could put something like a back arrow in the image section when its not hidden. 

Or should we just have another page to display the images so that navigating from the folders and back is intuitive?

**Comment by gwenf** [comment]
Hey @jmsMaupin1 @mattattaq,

I updated the photo page to include photos pulled from meetup.com and added a sass file to style the page. This is just for temporary purposes, so please overwrite and make changes as you see fit.

Here are some things that need to be fixed:

* Images are not optimized
* We should have a lightbox when images are clicked on.
* Images should be organized in groups (eg hack-nights, code and coffees, meetups...)
* Images need to have labels
* Page header is ugly

There are probably lots of other things that should be fixed as well.

**Comment by gwenf** [comment]
We need to update the gallery with new photos.

**Comment by wmBolles** [comment]
hahaha that's funny
